# Generated by Django 3.0.8 on 2020-08-02 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='individual_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('user_rating', models.FloatField(blank=True, null=True)),
                ('analyser_result', models.FloatField(blank=True, null=True)),
                ('average_result', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_analyser_result', models.FloatField(blank=True, null=True)),
                ('overall_user_rating', models.FloatField(blank=True, null=True)),
                ('overall_average_result', models.FloatField(blank=True, null=True)),
                ('csv_file', models.FileField(upload_to='uploads/')),
                ('is_ready', models.BooleanField(default=False)),
                ('individual_review_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentiment_analysis.individual_result')),
            ],
        ),
    ]
