# Generated by Django 3.0.8 on 2020-08-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='individual_result',
            new_name='IndividualResult',
        ),
    ]
