# Generated by Django 3.0.8 on 2020-08-02 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment_analysis', '0002_auto_20200802_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='individual_review_result',
        ),
        migrations.AddField(
            model_name='individualresult',
            name='overall_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sentiment_analysis.Result'),
        ),
    ]
